// @ts-ignore
import ZKLib from 'zkteco-js';
import { prisma } from '../lib/prisma';
import bcrypt from 'bcryptjs';

// ─── Device Configuration ──────────────────────────────────────────────────────
// Configuration values are loaded dynamically in the functions to avoid Next.js build crashes.
const ZK_TIMEOUT = 40000; // Increased to 40s to prevent TIMEOUT_ON_WRITING_MESSAGE
const ZK_INPORT = 0; // Set to 0 to allow OS to pick an available port and avoid conflicts

// ─── Timezone Fix ─────────────────────────────────────────────────────────────
// The ZKTeco device sends timestamps in local Bangladesh time (UTC+6).
// JavaScript's `new Date(localTimeString)` treats a bare date string as UTC
// (or server-local time), which would make every punch appear 6 hours ahead
// of its true UTC equivalent.
// To fix: parse the device time as a Date, then subtract 6 hours to get the
// correct UTC moment before saving to Prisma.
const DHAKA_OFFSET_MS = 6 * 60 * 60 * 1000; // UTC+6 in milliseconds
// Replaces volatile server-timezone-dependent subtraction logic with exact numeric component parsing.
// Milliseconds are explicitly zeroed so that @@unique([employeeId, timestamp]) works correctly:
// two network packets for the same punch arriving at 10:19:18.123 and 10:19:18.456 both
// normalize to 10:19:18.000 and are treated as one record by skipDuplicates/upsert.
export const parseDeviceTime = (deviceDateInput: any): Date => {
  if (!deviceDateInput) return new Date(NaN);

  const deviceDate = new Date(deviceDateInput);
  if (isNaN(deviceDate.getTime())) return new Date(NaN);

  const y = deviceDate.getFullYear();
  const m = String(deviceDate.getMonth() + 1).padStart(2, '0');
  const d = String(deviceDate.getDate()).padStart(2, '0');
  const h = String(deviceDate.getHours()).padStart(2, '0');
  const min = String(deviceDate.getMinutes()).padStart(2, '0');
  const s = String(deviceDate.getSeconds()).padStart(2, '0');

  // Build ISO string with +06:00 offset (device sends Dhaka local time)
  // The string intentionally omits milliseconds so the result is always .000
  const normalized = new Date(`${y}-${m}-${d}T${h}:${min}:${s}+06:00`);
  return normalized; // milliseconds = 0 by construction
};

// ─── Error Classification ──────────────────────────────────────────────────────
function classifyError(err: any): string {
  console.error('[ZKService] Raw Error:', err);
  const errorStr: string = typeof err === 'string' ? err : (err?.message || err?.toString() || '');
  const msg = errorStr.toLowerCase();
  if (msg.includes('econnrefused')) return 'Connection refused — device offline or wrong port.';
  if (msg.includes('etimedout') || msg.includes('timeout')) return 'Connection timed out — device unreachable on the network.';
  if (msg.includes('enotfound')) return 'Host not found — check the IP address.';
  if (msg.includes('subarray') || msg.includes('null')) return 'Device returned an unreadable packet. Check firmware compatibility.';
  return errorStr || 'Unknown ZKTeco device error.';
}

// ─── Factory ──────────────────────────────────────────────────────────────────
async function createZK(): Promise<InstanceType<typeof ZKLib>> {
  // @ts-ignore - The device model is dynamically generated by Prisma
  const device = await (prisma as any).device.findFirst({ where: { isActive: true } });

  if (!device) {
    throw new Error('No active ZKTeco device configured in the database. Please add a device in Settings > Device.');
  }

  const ZK_IP = device.ipAddress;
  const ZK_PORT = device.port || 4370;
  const ZK_PASSWORD = device.commKey || 0;

  const zk = new ZKLib(ZK_IP, ZK_PORT, ZK_TIMEOUT, ZK_INPORT);
  zk.password = ZK_PASSWORD;
  zk.connectionType = 'tcp'; // Prioritize TCP for stable payloads

  // Attach IP for logging
  (zk as any).deviceIp = ZK_IP;

  return zk;
}

// ─── Punch type resolver ───────────────────────────────────────────────────────
export function getPunchType(record: any): string {
  const punchType = (record.state === 0 || record.type === 0) ? 'CheckIn' : 'CheckOut';
  return punchType;
}

/**
 * Resolves the punch type chronologically, ignoring device state completely.
 *
 * Rules:
 *  - BULK SYNC path (punchHistory provided): uses an in-memory per-employee
 *    punch counter. Odd punch = CheckIn, Even punch = CheckOut.
 *    No time-gap filtering — every distinct device record is saved.
 *
 *  - REAL-TIME path (no punchHistory): queries the DB for today’s existing
 *    logs. Odd total = next is CheckOut, Even total = next is CheckIn.
 *    Only exact-same-second duplicates are blocked (handled by DB unique
 *    constraint + upsert in the caller). No 30-minute guard.
 */
export async function resolvePunchType(
  employeeId: string,
  timestamp: Date,
  log: any,
  batchState?: Map<string, { lastPunchType: string; timestamp: Date }>
): Promise<string | null> {
  const tzOffset = 6 * 60 * 60 * 1000;
  const localDate = new Date(timestamp.getTime() + tzOffset);
  const dateStr = `${localDate.getUTCFullYear()}-${localDate.getUTCMonth() + 1}-${localDate.getUTCDate()}`;
  const key = `${employeeId}_${dateStr}`;

  console.log("DEBUG_PUNCH_TYPE:", log.punchType ?? log.type);

  // 1. Try to map exact values from the device
  let exactDeviceType: string | null = null;
  const rawType = (log.punchType ?? log.type)?.toString().toUpperCase();
  
  if (rawType !== undefined && rawType !== null && rawType !== 'UNKNOWN' && rawType !== '') {
    if (['0', 'CHECKIN', 'CHECK-IN', 'IN'].includes(rawType)) {
      exactDeviceType = 'CheckIn';
    } else if (['1', 'CHECKOUT', 'CHECK-OUT', 'OUT', '4', '5'].includes(rawType)) {
      // Note: Some ZK devices use 4/5 for Overtime In/Out. Defaulting 1/OUT to CheckOut.
      exactDeviceType = 'CheckOut';
    } else {
      console.error(`[Worker] Unmapped punch type value: ${rawType} for employee ${employeeId}`);
    }
  }

  let lastKnownType: string | null = null;
  let lastKnownTime: Date | null = null;

  // 2. Fetch last known state for chronological fallback and duplicate detection
  if (batchState && batchState.has(key)) {
    const state = batchState.get(key)!;
    lastKnownType = state.lastPunchType;
    lastKnownTime = state.timestamp;
  } else {
    // Query DB
    const startOfDayLocal = new Date(Date.UTC(localDate.getUTCFullYear(), localDate.getUTCMonth(), localDate.getUTCDate(), 0, 0, 0, 0));
    const startOfTodayUTC = new Date(startOfDayLocal.getTime() - tzOffset);
    const endOfTodayUTC = new Date(startOfTodayUTC.getTime() + 24 * 60 * 60 * 1000 - 1);

    const lastLog = await prisma.attendanceLog.findFirst({
      where: {
        employeeId,
        timestamp: {
          gte: startOfTodayUTC,
          lte: endOfTodayUTC,
        },
      },
      orderBy: { timestamp: 'desc' },
    });

    if (lastLog) {
      lastKnownType = lastLog.punchType;
      lastKnownTime = lastLog.timestamp;
    }
  }

  // Block exact same-second duplicate from device
  if (lastKnownTime && timestamp.getTime() === lastKnownTime.getTime()) {
    return null; // exact duplicate
  }

  // 3. Resolve Final Type: Device Match OR Chronological Toggle
  let newPunchType = 'CheckIn';
  if (exactDeviceType) {
    newPunchType = exactDeviceType;
  } else {
    newPunchType = lastKnownType === 'CheckIn' ? 'CheckOut' : 'CheckIn';
  }

  // Save back to batch state for next loop iteration
  if (batchState) {
    batchState.set(key, { lastPunchType: newPunchType, timestamp });
  }

  return newPunchType;
}

/**
 * Self-healing routine to group today's logs by employeeId,
 * sort them by timestamp ascending, and strictly update the
 * earliest log to CheckIn and subsequent logs to CheckOut.
 */
export async function healTodaysData(): Promise<void> {
  try {
    const tzOffset = 6 * 60 * 60 * 1000;
    const nowBD = new Date(new Date().getTime() + tzOffset);
    const startBD = new Date(Date.UTC(nowBD.getUTCFullYear(), nowBD.getUTCMonth(), nowBD.getUTCDate(), 0, 0, 0, 0));
    const endBD = new Date(Date.UTC(nowBD.getUTCFullYear(), nowBD.getUTCMonth(), nowBD.getUTCDate(), 23, 59, 59, 999));

    const startOfToday = new Date(startBD.getTime() - tzOffset);
    const endOfToday = new Date(endBD.getTime() - tzOffset);

    // 1. Fetch all attendance logs for today
    const logs = await prisma.attendanceLog.findMany({
      where: {
        timestamp: {
          gte: startOfToday,
          lte: endOfToday,
        },
      },
      orderBy: {
        timestamp: 'asc',
      },
    });

    // 2. Group by employeeId
    const employeeLogs: Record<string, typeof logs> = {};
    for (const log of logs) {
      if (!employeeLogs[log.employeeId]) {
        employeeLogs[log.employeeId] = [];
      }
      employeeLogs[log.employeeId].push(log);
    }

    // 3. Update punchTypes: Earliest -> CheckIn, Rest -> CheckOut
    for (const employeeId in employeeLogs) {
      const list = employeeLogs[employeeId];
      if (list.length === 0) continue;

      // First log of the day becomes CheckIn
      const firstLog = list[0];
      await prisma.attendanceLog.update({
        where: { id: firstLog.id },
        data: { punchType: 'CheckIn' },
      });

      // Subsequent logs of the day become CheckOut (unless they are break or overtime)
      for (let i = 1; i < list.length; i++) {
        const log = list[i];
        if (['CheckIn', 'CheckOut'].includes(log.punchType)) {
          await prisma.attendanceLog.update({
            where: { id: log.id },
            data: { punchType: 'CheckOut' },
          });
        }
      }
    }
    console.log(`[zkService] 🏥 Healed today's attendance data for ${Object.keys(employeeLogs).length} employees.`);
  } catch (err: any) {
    console.error('❌ [healTodaysData] Error healing today\'s logs:', err);
  }
}

/**
 * Processes unassigned/unprocessed logs from RawDeviceLog into AttendanceLog
 * by grouping by employee and date, strictly enforcing chronological CheckIn/CheckOut toggling.
 */
export async function processRawDeviceLogs(): Promise<number> {
  let processedCount = 0;
  try {
    const rawLogs = await prisma.rawDeviceLog.findMany({
      orderBy: { recordTime: 'asc' }
    });

    if (rawLogs.length === 0) return 0;

    // Fetch mapped users
    const users = await prisma.user.findMany({
      where: { zktecoId: { not: null } },
      select: { id: true, zktecoId: true }
    });
    
    const zktecoIdToUserId = new Map<string, string>();
    for (const u of users) {
      if (u.zktecoId) zktecoIdToUserId.set(u.zktecoId.toString(), u.id);
    }

    const mappedLogs = rawLogs.filter(log => zktecoIdToUserId.has(log.deviceUserId));
    if (mappedLogs.length === 0) return 0;

    // Group mappedLogs by employeeId + YYYY-MM-DD
    const grouped: Record<string, typeof rawLogs> = {};
    const tzOffset = 6 * 60 * 60 * 1000; // UTC+6 Bangladesh
    
    for (const log of mappedLogs) {
      const empId = zktecoIdToUserId.get(log.deviceUserId)!;
      const localDate = new Date(log.recordTime.getTime() + tzOffset);
      const dateKey = `${localDate.getUTCFullYear()}-${localDate.getUTCMonth() + 1}-${localDate.getUTCDate()}`;
      const key = `${empId}_${dateKey}`;
      
      if (!grouped[key]) grouped[key] = [];
      grouped[key].push(log);
    }

    const newAttendanceLogs: any[] = [];
    const rawLogIdsToDelete: string[] = [];

    for (const key in grouped) {
      const logs = grouped[key];
      const empId = key.split('_')[0];
      
      // Sort chronologically (earliest to latest)
      logs.sort((a, b) => a.recordTime.getTime() - b.recordTime.getTime());

      const batchState = new Map<string, { lastPunchType: string; timestamp: Date }>();

      for (let i = 0; i < logs.length; i++) {
        const log = logs[i];

        // Deduplicate exact same-second punch within the same group
        if (i > 0 && log.recordTime.getTime() === logs[i-1].recordTime.getTime()) {
           rawLogIdsToDelete.push(log.id);
           continue; 
        }

        const punchType = await resolvePunchType(empId, log.recordTime, log as any, batchState);
        
        if (!punchType) {
           rawLogIdsToDelete.push(log.id);
           continue;
        }

        newAttendanceLogs.push({
          employeeId: empId,
          timestamp: log.recordTime,
          punchType: punchType,
          deviceId: log.ip || 'RAW_PROCESSOR',
        });
        
        console.log("SYNC_LOG_TYPE:", { userId: empId, timestamp: log.recordTime, type: punchType });
        
        rawLogIdsToDelete.push(log.id);
      }
    }

    if (newAttendanceLogs.length > 0) {
      const result = await prisma.attendanceLog.createMany({
        data: newAttendanceLogs,
        skipDuplicates: true // Ignores compound unique constraint violations safely
      });
      processedCount = result.count;
    }

    // Safely cleanup the raw logs that were processed/mapped
    if (rawLogIdsToDelete.length > 0) {
      // Chunk deletes to avoid large query limits if necessary, though typical sizes are small
      await prisma.rawDeviceLog.deleteMany({
        where: { id: { in: rawLogIdsToDelete } }
      });
    }

    console.log(`[ZKService] 🔄 Processed ${processedCount} raw logs into AttendanceLog and deleted mapped raw records.`);
  } catch (err: any) {
    console.error('❌ [processRawDeviceLogs] Pipeline Error:', err.message);
  }
  return processedCount;
}

// ─── Connection Helper ─────────────────────────────────────────────────────────────────
async function connectProperly(zk: any): Promise<void> {
  // Try TCP first
  try {
    zk.connectionType = 'tcp';
    if (zk.ztcp && typeof zk.ztcp.createSocket === 'function') {
      await zk.ztcp.createSocket();
    } else {
      await zk.createSocket();
    }
  } catch (err) {
    console.warn('[ZKService] TCP connection failed, falling back to UDP...');
    zk.connectionType = 'udp';
    if (zk.zudp && typeof zk.zudp.createSocket === 'function') {
      await zk.zudp.createSocket();
    } else {
      await zk.createSocket();
    }
  }

  // Give the socket a moment to breathe
  await new Promise(r => setTimeout(r, 1000));

  try {
    // Only call connect() if it actually exists in the library version
    if (typeof zk.connect === 'function') {
      await Promise.race([
        zk.connect(),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Connection timeout - device unreachable')), 5000))
      ]);
    }
    console.log(`[ZKService] 🔌 Connected using ${zk.connectionType.toUpperCase()}`);

    if (typeof zk.getRealTimeLogs === 'function') {
      zk.getRealTimeLogs((data: any) => {
        console.log('[ZKService] 🕒 Real-time Log Received:', data);
      });
    }
  } catch (error: any) {
    console.error('[ZKTeco Connection Error]:', error.message);
    throw error;
  }
}

// ─── Helper to fetch raw users directly ───────────────────────────────────────
async function getDeviceUsersRaw(zk: any): Promise<any[]> {
  try {
    const response = await zk.getUsers();
    console.log(`[ZKService] 🔍 Raw Users Response (${zk.connectionType.toUpperCase()}):`, JSON.stringify(response, null, 2));
    const { data } = response;
    const users = Array.isArray(data) ? data : [];

    // K60 firmware quirk: UDP sometimes returns empty user list even when users exist.
    // TCP fallback disabled as the device only supports UDP port 4370.
    if (users.length === 0 && zk.connectionType === 'udp') {
      console.warn('[ZKService] ⚠️ UDP returned 0 users. TCP fallback disabled due to UDP-only connectivity.');
    }

    return users;
  } catch (err) {
    console.warn('[ZKService] ⚠️ Failed to fetch users from device:', err);
    return [];
  }
}

/**
 * Robust wrapper for fetching attendance with retry logic
 */
async function getAttendanceAsync(zk: any): Promise<any[]> {
  let attempts = 3;
  while (attempts > 0) {
    try {
      const response = await zk.getAttendances();
      console.log('[ZKService] 🔍 Raw Attendance Response:', JSON.stringify(response, null, 2));
      const { data } = response;
      return Array.isArray(data) ? data : [];
    } catch (err: any) {
      const isTimeout = (err.message || '').includes('TIMEOUT');
      if (isTimeout && attempts > 1) {
        console.warn(`[ZKService] ⏳ Timeout detected. Retrying... (${attempts - 1} left)`);
        await new Promise(r => setTimeout(r, 3000)); // Wait 3s before retry
        attempts--;
        continue;
      }

      if (err.message === 'zero' || err.message === 'zero length reply') {
        console.log("[ZKService] ⚠️ ডিভাইস থেকে কোনো ডেটা পাওয়া যায়নি (Empty logs).");
        return [];
      }
      throw err;
    }
  }
  return [];
}

// ─── Public API ───────────────────────────────────────────────────────────────

let hasSanitizedManualLogs = false;

/**
 * Fetch attendance logs from device → upsert into MongoDB.
 */
export const getDeviceAttendance = async (): Promise<{ synced: number; skipped: number; total: number }> => {
  const zk = await createZK();
  const currentZkIp = (zk as any).deviceIp || 'Unknown IP';
  try {
    await connectProperly(zk);
    console.log(`[ZKService] ✅ Connected to ${currentZkIp} (${zk.connectionType})`);

    // Data sanitization logic has been removed as the root timezone bug is permanently resolved.

    // 1. Fetch Users from device (Mapping Phase)
    // Removed auto-upsert to enforce strict Hardware-to-Software mapping
    console.log('[ZKService] 👥 Fetching users from device for mapping...');
    const rawUsers = await getDeviceUsersRaw(zk);
    const userIdMap = new Map<string, string>(); // maps device employeeId -> User.id (UUID)

    // Load any other existing users in database into the userIdMap
    const dbUsers = await prisma.user.findMany({});
    for (const user of dbUsers) {
      if (user.employeeId) userIdMap.set(user.employeeId, user.id);
      if (user.zktecoId) userIdMap.set(String(user.zktecoId), user.id);
    }

    const rawLogs = await getAttendanceAsync(zk);

    // Delta Sync Optimization: Track Last Sync Time
    const latestLog = await prisma.attendanceLog.findFirst({ orderBy: { timestamp: 'desc' } });
    const lastSyncTime = latestLog ? latestLog.timestamp.getTime() : new Date('2000-01-01').getTime();

    // Backend-Level Filtering (Fallback) - Only process logs newer than the last synced record
    const recentLogs = rawLogs.filter((log: any) => {
      const deviceTime = log.timestamp || log.recordTime || log.record_time;
      if (!deviceTime) return false;
      
      const rawTimestamp = parseDeviceTime(deviceTime);
      rawTimestamp.setMilliseconds(0); // align with insertion logic

      return rawTimestamp.getTime() > lastSyncTime;
    });

    if (recentLogs.length === 0) {
      // Emit socket event to frontend via global.io
      const io = (global as any).io;
      if (io) {
        io.emit('attendanceUpdate', { checkIn: true });
      }
      return { synced: 0, skipped: 0, total: 0 };
    }
    console.log(`[ZKService] 📋 Delta Sync: ${recentLogs.length} new record(s) out of ${rawLogs.length} total on device.`);

    // Sort logs chronologically ascending (earliest to latest) to guarantee correct CheckIn/CheckOut determination
    const sortedRawLogs = Array.isArray(recentLogs) ? [...recentLogs].sort((a: any, b: any) => new Date(a.timestamp || a.recordTime || a.record_time).getTime() - new Date(b.timestamp || b.recordTime || b.record_time).getTime()) : [];

    let skipped = 0;

    // Track timestamps globally to prevent duplicate compound constraints on exact millisecond Architecture.
    // Track timestamps globally to prevent duplicate compound constraints on exact millisecond
    const usedTimestamps = new Set<string>();
    const formattedLogsArray: any[] = [];
    const unmappedLogsArray: any[] = [];
    const unmappedUsedTimestamps = new Set<string>();
    const batchState = new Map<string, { lastPunchType: string; timestamp: Date }>();

    for (const log of sortedRawLogs) {
      try {
        const deviceEmpId = String(log.deviceUserId ?? log.user_id ?? log.userId ?? log.uid);

        if (!log.recordTime && !log.timestamp && !log.record_time) {
          console.log("[ZKService] ⚠️ Skipping empty heartbeat packet...");
          skipped++;
          continue;
        }

        const deviceTime = log.timestamp || log.recordTime || log.record_time;

        // parseDeviceTime converts device-local Dhaka time → UTC and strips milliseconds.
        // The defensive setMilliseconds(0) below is a belt-and-suspenders guard: if any
        // future code path introduces sub-second jitter, it is zeroed here before the
        // @@unique([employeeId, timestamp]) constraint and createMany deduplicate on it.
        const rawTimestamp = parseDeviceTime(deviceTime);
        if (rawTimestamp.getMilliseconds() !== 0) {
          console.warn(`[ZKService] ⚠️ Non-zero ms detected (${rawTimestamp.getMilliseconds()}ms) — stripping. Raw: ${deviceTime}`);
        }
        rawTimestamp.setMilliseconds(0);
        const timestamp = rawTimestamp;

        if (isNaN(timestamp.getTime())) {
          skipped++;
          continue;
        }

        let employeeId = userIdMap.get(deviceEmpId);
        if (!employeeId) {
          // STRICT OPT-IN: Save unmapped device user punch safely without an employee profile
          const collisionKey = `${deviceEmpId}_${timestamp.getTime()}`;
          if (!unmappedUsedTimestamps.has(collisionKey)) {
            unmappedUsedTimestamps.add(collisionKey);
            unmappedLogsArray.push({
              deviceUserId: deviceEmpId,
              recordTime: timestamp,
              punchType: log.punchType !== undefined && log.punchType !== null ? String(log.punchType) : null,
              ip: currentZkIp,
            });
          }
          continue;
        }

        const punchType = await resolvePunchType(employeeId, timestamp, log, batchState);
        console.log("SYNC_LOG_TYPE:", { userId: employeeId, timestamp, type: punchType });

        if (!punchType) {
          skipped++;
          continue; // Exact-second duplicate — skipped by in-memory Set below
        }

        // In-memory dedup: last line of defence before createMany (skipDuplicates:true
        // in createMany + the DB unique constraint are the authoritative dedup).
        const collisionKey = `${employeeId}_${timestamp.getTime()}`;
        if (usedTimestamps.has(collisionKey)) {
          skipped++;
          continue;
        }
        usedTimestamps.add(collisionKey);

        formattedLogsArray.push({
          employeeId,
          timestamp,
          punchType: punchType as any,
          deviceId: currentZkIp,
        });

      } catch (err: any) {
        console.error(`[ZKService] ❌ Failed to format log:`, err.message);
        skipped++;
      }
    }

    // TASK 2: Convert to Bulk Insert (createMany)
    let synced = 0;
    if (formattedLogsArray.length > 0) {
      const result = await prisma.attendanceLog.createMany({
        data: formattedLogsArray,
        skipDuplicates: true, // Automatically ignores records that violate the Unique Constraint
      });
      synced = result.count;
      console.log(`[ZKService] ✅ Synced ${synced} mapped logs.`);
    }

    if (unmappedLogsArray.length > 0) {
      const rawResult = await prisma.rawDeviceLog.createMany({
        data: unmappedLogsArray,
        skipDuplicates: true,
      });
      console.log(`[ZKService] 🛡️ Safely stored ${rawResult.count} unmapped punches in RawDeviceLog.`);
      skipped += unmappedLogsArray.length; // From Attendance dashboard perspective, they are skipped/invisible
    }

    console.log(`[ZKService] ✔  Synced: ${synced} | Skipped: ${skipped} | Total Recent: ${sortedRawLogs.length}`);

    // Emit socket event to frontend via global.io for instant dashboard refresh
    const io = (global as any).io;
    if (io) {
      io.emit('attendanceUpdate', { synced, skipped });
      console.log('[ZKService] 📡 Emitted attendanceUpdate to frontend.');
    }

    return { synced, skipped, total: rawLogs.length };
  } catch (err: any) {
    const reason = classifyError(err);
    console.error(`[ZKService] ❌ ${reason}`);
    throw new Error(reason);
  } finally {
    try {
      if (zk && (zk.socket || (zk.zudp && zk.zudp.socket) || (zk.ztcp && zk.ztcp.socket))) {
        if (typeof zk.disconnect === 'function') {
          await zk.disconnect();
        } else if (typeof zk.free === 'function') {
          await zk.free();
        }
      }
    } catch (err: any) {
      console.error('[ZKService] ❌ Cleanup failed:', err.message);
    }
  }
};

/**
 * Fetch all users stored on the device and sync them to database.
 * Forced UDP because the device only supports UDP on port 4370.
 */
export const getDeviceUsers = async (): Promise<any[]> => {
  const zk = await createZK();
  try {
    await connectProperly(zk);
    const response = await zk.getUsers();
    console.log('[ZKService] 🔍 Raw Users Response (TCP):', JSON.stringify(response, null, 2));
    const { data } = response;
    const users: any[] = (data ?? []).map((u: any) => ({
      userId: String(u.user_id ?? u.userId ?? u.uid),
      name: u.name,
      role: u.role
    }));

    if (users.length === 0) {
      console.warn('[ZKService] ⚠️ Device returned 0 users via TCP. The device user list may be empty or firmware returned no data.');
    }

    // Removed auto-upsert to enforce strict Hardware-to-Software mapping
    console.log(`[ZKService] 👥 ${users.length} raw user(s) fetched from device.`);
    return users;
  } catch (err: any) {
    throw new Error(classifyError(err));
  } finally {
    try {
      if (zk && (zk.socket || (zk.zudp && zk.zudp.socket) || (zk.ztcp && zk.ztcp.socket))) {
        if (typeof zk.disconnect === 'function') {
          await zk.disconnect();
        } else if (typeof zk.free === 'function') {
          await zk.free();
        }
      }
    } catch (err: any) {
      console.error('[ZKService] ❌ Cleanup failed:', err.message);
    }
  }
};

/**
 * Non-destructive ping — verifies connectivity.
 */
export const pingDevice = async (): Promise<{ reachable: boolean; info?: any; error?: string; connectionType?: string }> => {
  const zk = await createZK();
  try {
    await connectProperly(zk);
    return { reachable: true, connectionType: zk.connectionType };
  } catch (err: any) {
    return { reachable: false, error: classifyError(err) };
  } finally {
    try {
      if (zk && (zk.socket || (zk.zudp && zk.zudp.socket) || (zk.ztcp && zk.ztcp.socket))) {
        if (typeof zk.disconnect === 'function') {
          await zk.disconnect();
        } else if (typeof zk.free === 'function') {
          await zk.free();
        }
      }
    } catch (err: any) {
      console.error('[ZKService] ❌ Cleanup failed:', err.message);
    }
  }
};

/** Legacy alias */
export const fetchDeviceLogs = async (): Promise<number> => {
  const { synced } = await getDeviceAttendance();
  return synced;
};

// ─── TASK 1: ZKTeco Device Synchronization ─────────────────────────────────────

export class ZKDeviceOfflineError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ZKDeviceOfflineError';
  }
}

export interface EmployeePayload {
  // WHY: The user requested id: number, but Prisma schema defines User.id as String (UUID).
  id: string;
  zktecoId: number;
  name: string;
  password?: string;
  role?: 0 | 14;
}

export interface SyncResult {
  success: boolean;
  action: 'created' | 'updated';
  enrollNumber: number;
}

/**
 * Reusable helper to manage ZKTeco connections safely.
 * @param fn Callback to execute with the connected ZK instance.
 */
export async function withZKConnection<T>(fn: (zk: any) => Promise<T>): Promise<T> {
  const zk = await createZK();
  try {
    try {
      await connectProperly(zk);
    } catch (err: any) {
      throw new ZKDeviceOfflineError('Failed to connect to ZK device: ' + classifyError(err));
    }

    return await fn(zk);
  } finally {
    try {
      if (zk && (zk.socket || (zk.zudp && zk.zudp.socket) || (zk.ztcp && zk.ztcp.socket))) {
        if (typeof zk.disconnect === 'function') {
          await zk.disconnect();
        } else if (typeof zk.free === 'function') {
          await zk.free();
        }
      }
    } catch (err: any) {
      console.error('[ZKService] ❌ Cleanup failed in withZKConnection:', err.message);
    }
  }
}

/**
 * Syncs a user to the ZKTeco device, acting as an upsert.
 * @param employee The employee data to sync.
 */
async function syncUserToDevice(employee: EmployeePayload): Promise<SyncResult> {
  // Validate enrollNumber
  if (!Number.isInteger(employee.zktecoId) || employee.zktecoId < 1 || employee.zktecoId > 32767) {
    throw new TypeError(`Invalid zktecoId: ${employee.zktecoId}. Must be an integer between 1 and 32767.`);
  }

  return await withZKConnection(async (zk) => {
    // 1. Fetch the user directly from the DB to get the freshest data.
    // WHY: Avoid stale data from the request payload and ensure the mapping is correct.
    const dbUser = await prisma.user.findUnique({
      where: { id: employee.id }
    });

    if (!dbUser) {
      throw new Error(`User with ID ${employee.id} not found in DB.`);
    }

    const enrollNumber = (dbUser as any).zktecoId;
    if (!enrollNumber || enrollNumber === 0) {
      console.warn(`[ZKService] Employee ${employee.id} has no ZKTeco enroll number assigned. Bypassing sync.`);
      return { success: false, action: 'created', enrollNumber: 0 };
    }

    // 2. Fetch existing users from the device
    const existingUsers = await getDeviceUsersRaw(zk);
    const existingEnrollNumbers = existingUsers.map((u: any) => parseInt(u.userId || u.uid || u.user_id, 10));

    // Determine if it's a create or update
    const action = existingEnrollNumbers.includes(enrollNumber) ? 'updated' : 'created';

    // 3. Prepare data
    // Truncate name safely to 24 chars
    const safeName = (employee.name || dbUser.name).substring(0, 24);
    const password = employee.password || '0';
    const role = employee.role ?? (dbUser.designationId ? 0 : 0); // Default to user if not specified

    // 4. Set User (Upsert)
    try {
      await zk.setUser(enrollNumber, enrollNumber.toString(), safeName, password, role);
      console.log(`[ZKService] User ${safeName} (Enroll: ${enrollNumber}) ${action} on device.`);
    } catch (err: any) {
      console.error(`[ZKService] Failed to set user ${enrollNumber}:`, err);
      throw new Error(`Failed to set user on device: ${err.message || err.toString()}`);
    }

    return { success: true, action, enrollNumber };
  });
}

/**
 * Deletes a user from the ZKTeco device by enrollNumber.
 * @param enrollNumber The ZKTeco enrollNumber to delete.
 */
async function deleteUserFromDevice(enrollNumber: number): Promise<void> {
  if (!Number.isInteger(enrollNumber) || enrollNumber < 1 || enrollNumber > 32767) {
    throw new TypeError(`Invalid zktecoId: ${enrollNumber}. Must be an integer between 1 and 32767.`);
  }

  await withZKConnection(async (zk) => {
    try {
      // Library method might differ, usually deleteUser takes the ID as string or number
      await zk.deleteUser(enrollNumber);
      console.log(`[ZKService] User ${enrollNumber} deleted from device.`);
    } catch (err: any) {
      console.error(`[ZKService] Failed to delete user ${enrollNumber}:`, err);
      throw new Error(`Failed to delete user on device: ${err.message || err.toString()}`);
    }
  });
}

export const fetchUnregisteredDeviceUsers = async (): Promise<{ deviceUserId: number; name: string }[]> => {
  return await withZKConnection(async (zk) => {
    const rawUsers = await getDeviceUsersRaw(zk);

    // Fetch registered enroll numbers
    const dbUsers = await prisma.user.findMany({
      select: { zktecoId: true }
    });
    const registeredIds = new Set(dbUsers.map(u => u.zktecoId).filter(Boolean));

    const unregistered = rawUsers.filter((u: any) => {
      const uid = parseInt(u.userId || u.uid || u.user_id, 10);
      return !registeredIds.has(uid);
    });

    return unregistered.map((u: any) => ({
      deviceUserId: parseInt(u.userId || u.uid || u.user_id, 10),
      name: u.name || `User ${parseInt(u.userId || u.uid || u.user_id, 10)}`
    }));
  });
};

export const zkService = {
  syncUserToDevice,
  deleteUserFromDevice,
  fetchUnregisteredDeviceUsers
};
